runtime: nodejs14

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /(.*\.(html|css))$
  static_files: \1
  upload: (.*\.(html|css))$
- url: /.*
  static_files: index.html
  upload: index.html